### ISSUE TITLE
Adding format and options of ws_user.conf to the manual.

### ISSUE THREAD

**Issue by Daraan** [holgerBerger/hpc-workspace#104]
Warnings about reminders state that the ~/.ws_user.conf can be modified, however there is not statement how. 
In the user guide it is also not explicitly written what and how it should be written.
My organization Wiki, and some others lacks such an info as well.
I think it would be helpful state in the manual that the options are:

```
mail:     <mailaddress>
reminder: <days>
```

**Comment by holgerBerger** [comment]
there is a short list of possible options in the ws_allocate manpage, but I added a chapter to the user guide.
