### ISSUE TITLE
Feature request: Have env variables to set defaults

### ISSUE THREAD

**Issue by gdkrmr** [holgerBerger/hpc-workspace#115]
It would be nice if I could set my email and remind interval (and probably other things) to user defined default values. I.e. set
```
export WS_MAILADDRESS=john@doe.com
export WS_REMINDER=7
export WS_FILESYSEM=my_preferred_filesystem
...
```
in my `.bashrc` this way I won't have to remember argument names and save some typing later. This will also avoid possible typos for things like e.g. the email address.

**Comment by holgerBerger** [comment]
are you aware of the user config file?

from the ws_allocate manpage

~/.ws_user.conf user config file to store some default values. File format is yaml, possible keys are mail, duration, reminder and groupname.  Those values can be overwritten with  options  on  command‐line.

       Example:
              mail: user@domain
              reminder: 1
              groupname: boygroup
              duration: 10


I think the only thing missing might be a default filesystem, but that should be actually defined by the administrator.

**Comment by gdkrmr** [comment]
No, I wasn't, thanks! It solves my issue, so I am closing this. If you think this is a worthwhile feature feel free to reopen.
