### ISSUE TITLE
Implementing an additional comment field

### ISSUE THREAD

**Issue by Reuti** [holgerBerger/hpc-workspace#12]
As not all characters are allowed as name of a workspace, it would advantageous to have some kind of comment field attached to a workspace which could be set by _ws_allocate_ or later added/changed with the same command by an option -c.

This field should then be output also with _ws_list_.

**Comment by holgerBerger** [comment]
ok, not trivial, have to think about it.
db entry can be extended, but one has to be carefull with characters allowed in the comment, it should not mess up the yaml...

**Comment by holgerBerger** [comment]
done

**Comment by Reuti** [comment]
thx, nice done. Would it be possible, to change the comment too when reusing a workspace like with the -r option?

**Comment by Reuti** [comment]
OK, I see. One has to use `-x` to change the comment, just with a zero extension. But:

Using an already existing workspace without extension outputs `Info: reusing workspace.` and changes nothing. Shouldn’t this be more like an error message `Error: workspace already in use`. The info messages gives the impression that the command succeeded without `-x`.
