### ISSUE TITLE
A used “-” in the DB name or the workspace name will cripple the sent reminder

### ISSUE THREAD

**Issue by Reuti** [holgerBerger/hpc-workspace#13]
The examples suggest as name of the database a name like /tmp/lustre-db. Unfortunately this will produce a wrong result of dbentryfilename.split('-')[1] in ws_expirer to send a reminder, as it should be the second field in this special case [line 325/326].

In addition a “-” is a valid character in a workspace’s name. But the above command will then leave the second or further parts of the workspace’s name out.

Essentially a “-” should neither be used in the name of the database, nor in the name of the workspace.

Or: use a different character like “+” to separate <USER>+<WORKSPACE>+<TIMESTAMP> and scan for the “+”, as the “+” is already a forbidden character for the name of the workspace (and deny it’s use in the database name too).

**Comment by holgerBerger** [comment]
should be fixed
