### ISSUE TITLE
ws_restore -l outputs wrong date for "-l" if a “-” is used in the name of the workspace

### ISSUE THREAD

**Issue by Reuti** [holgerBerger/hpc-workspace#14]
Same issue like in #13: boost::is_any_off("-") looks for the “-”, which does not always return the correct field as timestamp.

**Comment by holgerBerger** [comment]
good hint, will check it.

**Comment by holgerBerger** [comment]
should be fixed.

**Comment by Reuti** [comment]
Thx, this is working now. BTW: there is another boost split in the procedure check_names, but I'm unsure when this one will be used – for some "ruh-test".
