### ISSUE TITLE
ws_release should set the expiration date to the actual date

### ISSUE THREAD

**Issue by Reuti** [holgerBerger/hpc-workspace#15]
Maybe this could be a configurable option if not all like it: when a user releases a workspace, he usually wants to get rid of it. So it would be suitable to wait only the keeptime until it’s finally deleted. For now it seems to wait first for the usual expiration date, and then the keeptime starts for another grace period in addition.

**Comment by holgerBerger** [comment]
interesting idea, yes... thanks for the hint!

**Comment by holgerBerger** [comment]
implemented, probably what is expected, so not as an option.
