### ISSUE TITLE
ws_extend asks for 2 or 4 arguments, but any four will be forwarded to ws_allocate

### ISSUE THREAD

**Issue by Reuti** [holgerBerger/hpc-workspace#17]
I'm not sure whether this is a real issue or a feature. ws_extend will forward either 2 or 4 arguments to ws_allocate. But despite the help text it won’t check for the first argument being a -F, in fact any four can be supplied and will gracefully be forwarded.

**Comment by holgerBerger** [comment]
any more complex version is welcome :-)
