### ISSUE TITLE
ws_* -V does not output the version

### ISSUE THREAD

**Issue by Reuti** [holgerBerger/hpc-workspace#20]
-DGIT_COMMIT_HASH=\"\" seems to be not set in flags.cmake, hence the version output has no version on output

**Comment by holgerBerger** [comment]
seems to work for me, 3.10.2

**Comment by Reuti** [comment]
Aha, I used the downloaded ZIP. There it might be missing. With a _git clone_ it’s set and output . But I get 3ea35f9 as version intstead of a plain 3.10.2
