### ISSUE TITLE
extension of non-existing workspace silently creates one

### ISSUE THREAD

**Issue by mstud** [holgerBerger/hpc-workspace#31]
From one of our users came the following comprehensible request:

When extending the lifetime of a non-existing WS it simply creates that workspace instead of giving an error message:

$ ws_extend my-nonexisting-project 10
Info: creating workspace.
/scratch/ws/username-my-nonexisting-project
remaining extensions  : 2
remaining time in days: 10
$ echo $?
0

That's dangerous if people don't read the info message closely and assume that the extension has finished successfully, but would then lose their real WS content because it wasn't extended. So I think this should not automatically create a workspace but just error out.

**Comment by holgerBerger** [comment]
fixed, but this might actually break existing workflows!
