### ISSUE TITLE
Workspace allocation with existing prefix changes parent directory

### ISSUE THREAD

**Issue by casio888** [holgerBerger/hpc-workspace#32]
When a prefix for the workspaces is set, the allocation changes the owner and grouup to the user's values to create a new directory. However, it does not change these back, so after allocating a workspace, a user owns the whole ws directory.

The uid in our code are hardcoded. It would be cleaner to catch them before changing them, holding them in variables and applying them from the variable.

Our fix is this part of code inserted into line 338 of src/ws.cpp:
```
if(prefix.length()>0) {  // in case we have a prefix, we change owner of that one back
    chown(wsdir_nopostfix.c_str(), 11, 4);
}
```

**Comment by holgerBerger** [comment]
hmmmmm.
why change the prefix dir in the first place?
I wonder why this is done...

Am Do., 12. Dez. 2019 um 09:41 Uhr schrieb casio888 <
notifications@github.com>:

**Comment by holgerBerger** [comment]
I can not reproduce that problem actually, can you provide some output
showing what exactly happens?

Am Do., 12. Dez. 2019 um 09:41 Uhr schrieb casio888 <
notifications@github.com>:

**Comment by holgerBerger** [comment]
I think this was fixed meanwhile.
