### ISSUE TITLE
submit a LICENSE file

### ISSUE THREAD

**Issue by gerd** [holgerBerger/hpc-workspace#36]
I am not sure if you provide the software for free.
If you provide your software for free and  not charge money for distributing copies of software then it would be nice that you provide a license file at the top level directory of the hpc-workspace software.
For example here is the license information of Fedora:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing

I suggest to copy the file from the URL
https://www.gnu.org/licenses/gpl-3.0.txt
and store it with the filename 'LICENSE' or 'Copyright' to your repository.

Also Github has some documentation of 'Licensing a repository':
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by holgerBerger** [comment]
file added
