### ISSUE TITLE
ws_restore lists all WS

### ISSUE THREAD

**Issue by mflehmig** [holgerBerger/hpc-workspace#37]
Currently, the tool 'ws_restore -l' lists restorable workspaces on the default file system. Workspaces on a certain file system can be listed by passing the option '-F ARG'.

It would be more consistent with respect to 'ws_list' and less error-prone for users to list all restorable workspaces on all file systems when 'ws_restore -l' is invoked without 'ARG'.

Can this be adopted?

**Comment by holgerBerger** [comment]
i will look into it, that is a bit complex.

**Comment by holgerBerger** [comment]
implemented but opened #40

**Comment by mflehmig** [comment]
Great!
