### ISSUE TITLE
Group Workspace Feature 

### ISSUE THREAD

**Issue by fbartusch** [holgerBerger/hpc-workspace#59]
Hi,

We're testing the newest hpc-workspace version for our new cluster and group workspaces would be a nice feature.
There is an unimplemented option in the current source code, so I wanted to ask if the group workspace feature will be implemented in the near future and how it will work.

Best Regards,
Felix

**Comment by holgerBerger** [comment]
I actually hope it works :-)

ws_allocate -g 

produces different permissions than without the -g, the workspace gets group readable
and should be listable by other member of the group.

       -g     a  group-workspace  will  be created, that is a workspace that can be seen by other members of current group with ws_list -g and
              the workspace itself is created group readable.

**Comment by fbartusch** [comment]
Thanks for the reply.Yes, it works. I didn't find anything in the user manual and nothing during a short glance in the code.

But it is not possible to choose a secondary group for the workspace? This is how we manage members of the same project.
Also, we set the group sticky bit (chmod g+s) on the folder, then new files in the directory also belong to the group.

**Comment by holgerBerger** [comment]
ok, I see....
working on it, needs some more testing.

**Comment by holgerBerger** [comment]
pushed meanwhile, see -G option.
