### ISSUE TITLE
NFS and root_squashing

### ISSUE THREAD

**Issue by staeglis** [holgerBerger/hpc-workspace#60]
Hi,

is it somehow possible to use workspaces on NFS with root-squashing enabled? At the I can get it running only if I disable it.

Best,
Stefan

**Comment by holgerBerger** [comment]
hmmmm i would hope it should work,
there was some changes necessary for lustre with root_squash,
I might have to do some tests.

Am Mo., 18. Jan. 2021 um 12:05 Uhr schrieb staeglis <
notifications@github.com>:

**Comment by holgerBerger** [comment]
should meanwhile work, there is some root_squash installations meanwhile.
