### ISSUE TITLE
Add possibility to share workspaces with other users in a safe and easy way

### ISSUE THREAD

**Issue by cniethammer** [holgerBerger/hpc-workspace#82]
Users often want to give other users, e.g., support staff, read access to
their workspaces.  Often these users are not in the same user group as the
owner of the workspace. Currently, the only way is to use standard UNIX permissions
and to grant read access for "other", which may be critical for some users.

So I suggest adding a new ws_share command for this that allows users to manage
access permissions for other users to their workspace hiding details of a more
sophisticated implementation, e.g., using Access Controll Lists (ACL).

Note: So far I think that granting read access should be sufficient.

A possible implementation is provided in PR #83

**Comment by holgerBerger** [comment]
pulled ws_share
