### ISSUE TITLE
Feature Request: default configuration file in user home

### ISSUE THREAD

**Issue by devreal** [holgerBerger/hpc-workspace#91]
I was wondering if it  was possible to have a per-user configuration file that is read in `ws_allocate` for example. One use for it would be to set default notifications instead of having to specify the same options over and over again (and potentially forgetting to do so for some).

Example:

```
$ cat ~/.ws_config
# my email address to send reminders to
-m name@domain.com
# Days to send reminder before expiration
-r 3 
# Default duration
-d 30
# Group workspace to use
-g mygroup
```

Command line options would override options in the config file.

**Comment by holgerBerger** [comment]
this feature partially existed in form of ~/.ws_user.conf file, it was able to contain the email address.
It was now extended to be able to contain reminder and duration as well, as well as groupname.
The groupname part might be actually a mistake, have to think about that...
contained in master and release 1.4.0
format is a bit different, it is yaml:
duration: 10
reminder: 1
mail: hey@you

very old format where the file contains only format (without prefixed mail:) gives an message and it is ignored.

**Comment by holgerBerger** [comment]
yes, the groupname is a stupid mistake as it is, as the -G options requires an argument.
The option in the file does NOT imply -G as of now, so it does actually nothing.
I am not sure if that is something people should be encouraged to have in their defaults,
I might remove that as well if there is no good ideas why this would be really a good thing to have.

**Comment by holgerBerger** [comment]
the last comment is wrong, the groupname IS implying the -G option and does make every workspace writable.

I have doubts this makes a lot of sense, I will probably add a good visible warning for that feature.
